export const CARDS = [
  {
    cardId: crypto.randomUUID(),
    question: "Will you be my valentine?",
    message: "Please do not say no to this proposal.",
    image: "/image.png",
    from: "John Doe",
    to: "Jane Doe",
    status: "pending",
    creatorEmail: "john.doe@example.com",
    createdAt: "2024-02-01",
  },
  {
    cardId: crypto.randomUUID(),
    question: "Happy Valentine's Day, my love!",
    message: "Every day with you feels like Valentine's Day. I love you!",
    image: "/image.png",
    from: "Alice Smith",
    to: "Bob Johnson",
    status: "accepted",
    creatorEmail: "alice.smith@example.com",
    createdAt: "2024-02-02",
  },
  {
    cardId: crypto.randomUUID(),
    question: "Be mine forever?",
    message: "Life is better with you in it. Be my valentine!",
    image: "/image.png",
    from: "Emma Wilson",
    to: "Michael Brown",
    status: "pending",
    creatorEmail: "emma.wilson@example.com",
    createdAt: "2024-02-03",
  },
  {
    cardId: crypto.randomUUID(),
    question: "You are my heart!",
    message: "Every beat of my heart is for you. Happy Valentine's Day!",
    image: "/image.png",
    from: "David Lee",
    to: "Sophia Green",
    status: "pending",
    creatorEmail: "david.lee@example.com",
    createdAt: "2024-02-04",

  },
  {
    cardId: crypto.randomUUID(),
    question: "You stole my heart!",
    message: "I don’t want it back! I just want to be yours forever.",
    image: "/image.png",
    from: "Chris Adams",
    to: "Olivia Martinez",
    status: "accepted",
    creatorEmail: "chris.adams@example.com",
    createdAt: "2024-02-05",
  },
  {
    cardId: crypto.randomUUID(),
    question: "A valentine just for you!",
    message: "I can't imagine my life without you. Happy Valentine's!",
    image: "/image.png",
    from: "Nathan Scott",
    to: "Emily Davis",
    status: "accepted",
    creatorEmail: "nathan.scott@example.com",
    createdAt: "2024-02-06",

  },
  {
    cardId: crypto.randomUUID(),
    question: "My love for you grows stronger!",
    message: "Another Valentine's Day with you is a blessing. I love you!",
    image: "/image.png",
    from: "Samantha White",
    to: "James Anderson",
    status: "pending",
    creatorEmail: "samantha.white@example.com",
    createdAt: "2024-02-07",

  },
  {
    cardId: crypto.randomUUID(),
    question: "You're the sweetest valentine!",
    message: "Like chocolate, you make my life sweeter. Love you always!",
    image: "/image.png",
    from: "Ryan Carter",
    to: "Laura Hall",
    status: "pending",
    creatorEmail: "ryan.carter@example.com",
    createdAt: "2024-02-08",
  },
  {
    cardId: crypto.randomUUID(),
    question: "You're my everything!",
    message:
      "On this special day, I just want to remind you how much you mean to me.",
    image: "/image.png",
    from: "Ethan Young",
    to: "Grace Walker",
    status: "accepted",
    creatorEmail: "ethan.young@example.com",
    createdAt: "2024-02-09",
  },
  {
    cardId: crypto.randomUUID(),
    question: "Let's make more Valentine's memories!",
    message: "From our first date to now, I cherish every moment with you.",
    image: "/image.png",
    from: "Liam Roberts",
    to: "Sophia Bennett",
    status: "accepted",
    creatorEmail: "liam.roberts@example.com",
    createdAt: "2024-02-10",
  },
];
